# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import devices_pb2 as devices__pb2


class Device_InformationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Network = channel.unary_unary(
        '/networks.Device_Information/Network',
        request_serializer=devices__pb2.Info.SerializeToString,
        response_deserializer=devices__pb2.Info.FromString,
        )


class Device_InformationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Network(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_Device_InformationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Network': grpc.unary_unary_rpc_method_handler(
          servicer.Network,
          request_deserializer=devices__pb2.Info.FromString,
          response_serializer=devices__pb2.Info.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'networks.Device_Information', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
