# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: devices.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='devices.proto',
  package='networks',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rdevices.proto\x12\x08networks\"\"\n\x04Info\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t2A\n\x12\x44\x65vice_Information\x12+\n\x07Network\x12\x0e.networks.Info\x1a\x0e.networks.Info\"\x00\x62\x06proto3')
)




_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='networks.Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='networks.Info.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role', full_name='networks.Info.role', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['Info'] = _INFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), dict(
  DESCRIPTOR = _INFO,
  __module__ = 'devices_pb2'
  # @@protoc_insertion_point(class_scope:networks.Info)
  ))
_sym_db.RegisterMessage(Info)



_DEVICE_INFORMATION = _descriptor.ServiceDescriptor(
  name='Device_Information',
  full_name='networks.Device_Information',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=63,
  serialized_end=128,
  methods=[
  _descriptor.MethodDescriptor(
    name='Network',
    full_name='networks.Device_Information.Network',
    index=0,
    containing_service=None,
    input_type=_INFO,
    output_type=_INFO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEVICE_INFORMATION)

DESCRIPTOR.services_by_name['Device_Information'] = _DEVICE_INFORMATION

# @@protoc_insertion_point(module_scope)
