FROM ubuntu:18.04

WORKDIR /nynoc-oc/flask/

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev

COPY  flask/. /nynoc-oc/flask/

RUN pip install -r requirements.txt

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]


